name: AI Doc Review

on:
  workflow_dispatch:

  issue_comment:
    types:
      - created

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' ||
      (
        github.event_name == 'issue_comment' &&
        contains(github.event.comment.body, '/bot-review') &&
        contains('hfxsd,likidu,lilin90,Oreoxmt,qiancai', github.event.comment.user.login)
      )
    outputs:
      zh_files_count: ${{ steps.diff.outputs.zh_files_count }}
      en_files_count: ${{ steps.diff.outputs.en_files_count }}
      review_mode: ${{ steps.extract.outputs.REVIEW_MODE }}
      commit_sha: ${{ steps.extract.outputs.COMMIT_SHA }}
      base_sha: ${{ steps.extract.outputs.BASE_SHA }}
      head_sha: ${{ steps.extract.outputs.HEAD_SHA }}
    steps:
      - name: Debug Info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event type: ${{ github.event.action }}"
          echo "Comment body: ${{ github.event.comment.body || 'No comment body' }}"
          echo "Comment author: ${{ github.event.comment.user.login || 'No user' }}"

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Extract review parameters
        id: extract
        if: github.event_name == 'issue_comment'
        run: |
          COMMENT="${{ github.event.comment.body }}"
          echo "Raw comment: $COMMENT"

          # Match commit range
          if [[ "$COMMENT" =~ \/bot-review:[[:space:]]*([a-f0-9]{7,40})[[:space:]]*\.\.[[:space:]]*([a-f0-9]{7,40}) ]]; then
            echo "BASE_SHA=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
            echo "HEAD_SHA=${BASH_REMATCH[2]}" >> $GITHUB_OUTPUT
            echo "REVIEW_MODE=commit_range" >> $GITHUB_OUTPUT
            echo "Detected commit range with regex: ${BASH_REMATCH[1]}..${BASH_REMATCH[2]}"

          # Match a single commit
          elif [[ "$COMMENT" =~ \/bot-review:[[:space:]]+([a-f0-9]{7,40}) ]]; then
            echo "COMMIT_SHA=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
            echo "REVIEW_MODE=single_commit" >> $GITHUB_OUTPUT
            echo "Detected single commit: ${BASH_REMATCH[1]}"

          # Match "/bot-review" or "/bot-review "
          elif [[ "$COMMENT" =~ ^\/bot-review[[:space:]]*$ ]]; then
            echo "REVIEW_MODE=latest" >> $GITHUB_OUTPUT
            echo "Detected default review mode"

          # Invalid format
          else
            echo "REVIEW_MODE=invalid" >> $GITHUB_OUTPUT
            echo "Invalid bot-review command format"
          fi

          echo "Parameters output:"
          cat $GITHUB_OUTPUT

      - name: Get PR diff
        id: diff
        run: |
          echo "Getting PR diff to check file paths..."
          echo "Event name: ${{ github.event_name }}"
          echo "Review mode: ${{ steps.extract.outputs.REVIEW_MODE }}"

          # Initialize variables
          PR_NUMBER=""
          FILES=""

          # Get PR number
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Workflow triggered manually by workflow_dispatch"
            if [[ "${{ github.ref }}" =~ ^refs/pull/([0-9]+)/merge$ ]]; then
              PR_NUMBER="${BASH_REMATCH[1]}"
              echo "Extracted PR number from github.ref: $PR_NUMBER"
            else
              echo "Not running on a PR branch: ${{ github.ref }}"
              echo "zh_files_count=0" >> $GITHUB_OUTPUT
              echo "en_files_count=0" >> $GITHUB_OUTPUT
              exit 0
            fi
          else
            # For issue_comment event
            PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH" || jq --raw-output .issue.number "$GITHUB_EVENT_PATH")
            echo "Extracted PR number from event path: $PR_NUMBER"
          fi

          if [[ -n "$PR_NUMBER" && "$PR_NUMBER" != "null" ]]; then
            echo "Using PR number: $PR_NUMBER"

            # Get file list based on REVIEW_MODE
            REVIEW_MODE="${{ steps.extract.outputs.REVIEW_MODE }}"

            if [[ "$REVIEW_MODE" == "single_commit" ]]; then
              # Get files for a single commit
              COMMIT_SHA="${{ steps.extract.outputs.COMMIT_SHA }}"
              echo "Getting files for single commit: $COMMIT_SHA"
              
              # Try local first
              FILES=$(git diff-tree --no-commit-id --name-only -r $COMMIT_SHA 2>/dev/null || echo "")
              
              # If no files found, fetch and try again
              if [[ -z "$FILES" ]]; then
                echo "No files found locally for commit $COMMIT_SHA, fetching from remote"
                if git fetch --depth=1 origin $COMMIT_SHA; then
                  echo "Fetch successful, getting files again"
                  FILES=$(git diff-tree --no-commit-id --name-only -r $COMMIT_SHA 2>/dev/null || echo "")
                  
                  if [[ -z "$FILES" ]]; then
                    echo "WARNING: Still no files found after fetch for commit $COMMIT_SHA"
                    echo "Attempting alternative approach with git show"
                    FILES=$(git show --name-only --format="" $COMMIT_SHA 2>/dev/null || echo "")
                  fi
                else
                  echo "ERROR: Failed to fetch commit $COMMIT_SHA"
                fi
              fi
              
              # Log files found for debugging
              echo "Files found for commit $COMMIT_SHA:"
              echo "$FILES"
            elif [[ "$REVIEW_MODE" == "commit_range" ]]; then
              # Get files for a commit range
              BASE_SHA="${{ steps.extract.outputs.BASE_SHA }}"
              HEAD_SHA="${{ steps.extract.outputs.HEAD_SHA }}"
              echo "Getting files for commit range: $BASE_SHA..$HEAD_SHA"

              # Try local first
              FILES=$(git diff --name-only $BASE_SHA $HEAD_SHA 2>/dev/null || echo "")
              
              # If no files found, fetch and try again
              if [[ -z "$FILES" ]]; then
                echo "No files found locally for range $BASE_SHA..$HEAD_SHA, fetching from remote"
                if git fetch --depth=1 origin $BASE_SHA $HEAD_SHA; then
                  echo "Fetch successful, getting files again"
                  FILES=$(git diff --name-only $BASE_SHA $HEAD_SHA 2>/dev/null || echo "")
                  
                  if [[ -z "$FILES" ]]; then
                    echo "WARNING: Still no files found after fetch for range $BASE_SHA..$HEAD_SHA"
                  fi
                else
                  echo "ERROR: Failed to fetch commits for range $BASE_SHA..$HEAD_SHA"
                fi
              fi
              
              # Log files found for debugging
              echo "Files found for commit range $BASE_SHA..$HEAD_SHA:"
              echo "$FILES"
            else
              # Default: get files for the entire PR
              echo "Getting files for entire PR"
              FILES=$(gh pr view $PR_NUMBER --repo ${{ github.repository }} --json files --jq '.files[].path')
            fi

            # Count Chinese and English files
            echo "Counting files in zh/ and en/ directories..."
            
            # Use grep to find zh/ and en/ files and save the output for logging
            ZH_FILES=$(echo "$FILES" | grep "^zh/" || echo "")
            EN_FILES=$(echo "$FILES" | grep "^en/" || echo "")
            
            # Count the files
            ZH_COUNT=$(echo "$ZH_FILES" | grep -c "^" || echo "0")
            EN_COUNT=$(echo "$EN_FILES" | grep -c "^" || echo "0")

            echo "Changed files (total):"
            echo "$FILES"
            echo "------------------------------"
            echo "Chinese files found ($ZH_COUNT):"
            echo "$ZH_FILES"
            echo "------------------------------"
            echo "English files found ($EN_COUNT):"
            echo "$EN_FILES"
            echo "------------------------------"

            echo "zh_files_count=$ZH_COUNT" >> $GITHUB_OUTPUT
            echo "en_files_count=$EN_COUNT" >> $GITHUB_OUTPUT
          else
            echo "Could not determine PR number, setting defaults for review"
            echo "zh_files_count=0" >> $GITHUB_OUTPUT
            echo "en_files_count=0" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  review-zh:
    needs: prepare
    if: needs.prepare.outputs.zh_files_count > 0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: AI Doc Reviewer for Chinese docs
        uses: qiancai/ai-codereviewer@main
        continue-on-error: false
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_PROVIDER: "deepseek"
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          DEEPSEEK_API_MODEL: "deepseek-chat"
          exclude: "**/*.json,!zh/**"
          REVIEW_MODE: ${{ needs.prepare.outputs.review_mode }}
          COMMIT_SHA: ${{ needs.prepare.outputs.commit_sha }}
          BASE_SHA: ${{ needs.prepare.outputs.base_sha }}
          HEAD_SHA: ${{ needs.prepare.outputs.head_sha }}
          PROMPT_PATH: "doc-review-prompt-zh.txt"

  review-en:
    needs: prepare
    if: needs.prepare.outputs.en_files_count > 0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: AI Doc Reviewer for English docs
        uses: qiancai/ai-codereviewer@main
        continue-on-error: false
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_PROVIDER: "openai"
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4"
          exclude: "**/*.json,zh/**"
          include: "en/**"  # Only include English docs
          REVIEW_MODE: ${{ needs.prepare.outputs.review_mode }}
          COMMIT_SHA: ${{ needs.prepare.outputs.commit_sha }}
          BASE_SHA: ${{ needs.prepare.outputs.base_sha }}
          HEAD_SHA: ${{ needs.prepare.outputs.head_sha }}
          PROMPT_PATH: "doc-review-prompt-en.txt"
